language: perl6

os:
  - linux
  - osx

perl6:
  - 2019.03.1
  - latest

install:
  - rakudobrew build zef
  - zef --depsonly install .
  - zef install Test::META

script: 
  - AUTHOR_TESTING=1 prove -v -e "perl6 -Ilib" t/
  - zef install .

